# 数据库连接信息
database:
  user: "root"
  password: "123456"
  host: "127.0.0.1"
  port: "3306"
  database: "test"

tables:
  guard_table: "list_aa"
  acc_table: "list_bb"

bilibili:
  uid: "34055779"
  roomid: "379598"
  cookie: "111"